version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:5.0
    container_name: futures-trading-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: futures123456
      MONGO_INITDB_DATABASE: futures-trading
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - futures-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: futures-trading-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - futures-network

  # 主应用
  app:
    build: .
    container_name: futures-trading-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:futures123456@mongodb:27017/futures-trading?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: futures-trading-jwt-secret-key-2024
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://38.180.94.137:3001
    depends_on:
      - mongodb
      - redis
    networks:
      - futures-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: futures-trading-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - futures-network

volumes:
  mongodb_data:
  redis_data:

networks:
  futures-network:
    driver: bridge
